approvedGitRepositories:
  - "**"

changesetBaseRefs:
  - main
  - origin/main
  - upstream/main

enableGlobalCache: false

enableScripts: true

enableTelemetry: false

pnpMode: loose

yarnPath: .yarn/releases/yarn-4.14.1.cjs
