name: Docs # needed to securely identify the workflow

on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    permissions:
      contents: write
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
        with:
          lfs: true

      - name: Use Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable --immutable-cache --check-cache

      - name: Build
        run: yarn build

      - name: Build package docs
        run: yarn docs

      - name: Copy docs into deployment folder
        run: ./scripts/docs/copy_docs.sh

      - name: Deploy to GitHub pages
        if: github.ref == 'refs/heads/master'
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npx gh-pages@6 --message "Update docs [skip ci]" --dist docs_deployment -u "github-actions-bot <support+actions@github.com>" --nojekyll
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
